Drains.Web/Drains.Web/Controllers/AdressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Drains.Web.Data.EntityFramework;
using Drains.Web.Data.EntityFramework.Entities;

namespace Drains.Web.Controllers
{
    public class AdressesController : Controller
    {
        private DrainsStorageModel db = new DrainsStorageModel();

        // GET: Adresses
        public ActionResult Index()
        {
            return View(db.Adresses.ToList());
        }

        // GET: Adresses/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adress adress = db.Adresses.Find(id);
            if (adress == null)
            {
                return HttpNotFound();
            }
            return View(adress);
        }

        // GET: Adresses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Adresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Region,District,Location")] Adress adress)
        {
            if (ModelState.IsValid)
            {
                db.Adresses.Add(adress);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(adress);
        }

        // GET: Adresses/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adress adress = db.Adresses.Find(id);
            if (adress == null)
            {
                return HttpNotFound();
            }
            return View(adress);
        }

        // POST: Adresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Region,District,Location")] Adress adress)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adress).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(adress);
        }

        // GET: Adresses/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adress adress = db.Adresses.Find(id);
            if (adress == null)
            {
                return HttpNotFound();
            }
            return View(adress);
        }

        // POST: Adresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Adress adress = db.Adresses.Find(id);
            db.Adresses.Remove(adress);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Drains.Web/Drains.Web/Controllers/SuppliersAdressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Drains.Web.Data.EntityFramework;
using Drains.Web.Data.EntityFramework.Entities;

namespace Drains.Web.Controllers
{
    public class SuppliersAdressesController : Controller
    {
        private DrainsStorageModel db = new DrainsStorageModel();

        // GET: SuppliersAdresses
        public ActionResult Index()
        {
            var suppliersAdresses = db.SuppliersAdresses.Include(s => s.Street);
            return View(suppliersAdresses.ToList());
        }

        // GET: SuppliersAdresses/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuppliersAdress suppliersAdress = db.SuppliersAdresses.Find(id);
            if (suppliersAdress == null)
            {
                return HttpNotFound();
            }
            return View(suppliersAdress);
        }

        // GET: SuppliersAdresses/Create
        public ActionResult Create()
        {
            ViewBag.StreetId = new SelectList(db.Streets, "Id", "Street");
            return View();
        }

        // POST: SuppliersAdresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SuppliersCode,Build,Apartment,Phone1,Phone2,Phone3,Email1,Email2,NameSupplier,StreetId")] SuppliersAdress suppliersAdress)
        {
            if (ModelState.IsValid)
            {
                db.SuppliersAdresses.Add(suppliersAdress);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StreetId = new SelectList(db.Streets, "Id", "Street", suppliersAdress.StreetId);
            return View(suppliersAdress);
        }

        // GET: SuppliersAdresses/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuppliersAdress suppliersAdress = db.SuppliersAdresses.Find(id);
            if (suppliersAdress == null)
            {
                return HttpNotFound();
            }
            ViewBag.StreetId = new SelectList(db.Streets, "Id", "Street", suppliersAdress.StreetId);
            return View(suppliersAdress);
        }

        // POST: SuppliersAdresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SuppliersCode,Build,Apartment,Phone1,Phone2,Phone3,Email1,Email2,NameSupplier,StreetId")] SuppliersAdress suppliersAdress)
        {
            if (ModelState.IsValid)
            {
                db.Entry(suppliersAdress).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StreetId = new SelectList(db.Streets, "Id", "Street", suppliersAdress.StreetId);
            return View(suppliersAdress);
        }

        // GET: SuppliersAdresses/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SuppliersAdress suppliersAdress = db.SuppliersAdresses.Find(id);
            if (suppliersAdress == null)
            {
                return HttpNotFound();
            }
            return View(suppliersAdress);
        }

        // POST: SuppliersAdresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            SuppliersAdress suppliersAdress = db.SuppliersAdresses.Find(id);
            db.SuppliersAdresses.Remove(suppliersAdress);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Drains.Web/Drains.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Adress", "Index", "Adresses", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Streets", "Index", "Streets", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Suppliers", "Index", "SuppliersAdresses", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Personals", "Index", "Personals", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Contracts", "Index", "Contracts", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Keys", "Index", "Keys", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("SuppleirBanks", "Index", "SuppleirBanks", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Deliverys", "Index", "Deliverys", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Paids", "Index", "Paids", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Permissions", "Index", "Permissions", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Deliv_parom", "Index", "Deliv_parom", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>